### ISSUE TITLE
API review: Interface changes

### ISSUE THREAD

**Issue by muratg** [aspnet/Logging#121]
**ILoggerStructure**
- Rename interface to ILogValues
- Remove "Messages" property (and from its implementations as well)

**ILoggerProvider**
- Rename Create to CreateLogger

**ILoggerFactory**
- Rename Create to CreateLogger
- Rename CreateLogger method's param name from "name" to "categoryName"

**ILogger**
- Rename Write method to Log
- **Documentation** Write doc on why we don't have LogAsync method. (Glenn)

**ILogger of T**
- Document why this is here (for DI)
- T -> TCategoryName

**IConsole**
- Move to .Internals namespace

**ConsoleLoggerExtensions**
- Move to ILoggerFactory's namespace

**Comment by BrennanConroy** [comment]
Should we rename FormatLoggerStructure function to FormatLogValues?

**Comment by BrennanConroy** [comment]
IConsole to Microsoft.Framework.Logging.Console.Internal or Microsoft.Framework.Logging.Internal?

**Comment by BrennanConroy** [comment]
@glennc do you have an answer for these? Also, should the Documentation be made a different issue for you or do you have it written down/memorized

**Comment by BrennanConroy** [comment]
Should we move ConsoleLoggerFactoryExtensions.cs to the Logging project since we changed the namespace from Logging.Console to Logging?

**Comment by glennc** [comment]
* Documentation should be a different issue. Can you split and link it for me when you close this? Assign it to me.
* I think IConsole should go to Console.Internal. 
* Extension methods for a type in a given namespace should live in that types namespace, but not necessarily in the same repo. ConsoleLoggerFactory is in the logging namespace, so the extensions for it should be in the same namespace. Otherwise I need to add another using to get the extensions, which adds a discover-ability problem.

**Comment by yann-c-webcenter** [comment]
Types in the *.Internal namespace shouldn't be "internal' instead of public ?

**Comment by ycrumeyrolle** [comment]
Types in the *.Internal namespaces shouldn't be internal instead of public ?
