### ISSUE TITLE
Add some space in the LogLevel enumeration and flip the values

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/Logging#131]
Proposal: Critical = 0, Error = 10000, Warning = 20000, and so on.

This has a few advantages over the current stack. First, `default(LogLevel)` signifies "record only critical failures", which seems an appropriate default if the developer didn't specify an explicit level. Second, adding extra space gives us room to add new levels in the future. Third, it allows you to think of the log level as a measure of verbosity, so the condition `if (level >= LogLevel.Warning)` naturally correlates to "only log this if the current verbosity level is at least 'Warning'".

/cc @BrennanConroy @lukewaters

**Comment by Eilon** [comment]
Not sure why we'd ever inject more log levels - I'm not sure what the semantic would be if we ever added a new one. Similarly for the order, the world seems to be split between high->low and low->high. It's easy to argue the ordering should be "most severe is biggest because it's the most important" but it's just as easy to argue as "most verbose is biggest because it's the most messages".

**Comment by davidfowl** [comment]
Yea, these level types are pretty standard across the most popular logging technologies on .NET today.

**Comment by GrabYourPitchforks** [comment]
Shall we close then?

**Comment by Eilon** [comment]
Yeah I'm not sure there's any clear benefit to these suggestions over what we currently have.
