### ISSUE TITLE
Documentation - Do not tell to log sensitive data

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Logging#154]
To log sensitive data is a bad practice. To log password is a security issue. 
The Guidelines page must not tell such things, even for the debug log level.

**Comment by glennc** [comment]
Do you mean this page: https://github.com/aspnet/Logging/wiki/Guidelines

The reason that is there is because Entity Framework will write the values of SQL statements to the debug log level. These could contain something that's sensitive, though they may not. It doesn't mean people should log passwords. We could probably make that clearer.

**Comment by ycrumeyrolle** [comment]
Yes, I was meaning this (very useful) page.

Maybe a new entry in the guidelines list could clarify the situation, by saying that sensitive data such password or credit card number should/must not be logged as is, or something like this. 
And by replacing the debug example with the password by another field, like first name?

**Comment by glennc** [comment]
@ycrumeyrolle Does that make it clear enough for you?

**Comment by ycrumeyrolle** [comment]
:+1:
