### ISSUE TITLE
Logging and DI

### ISSUE THREAD

**Issue by danroth27** [aspnet/Logging#220]
Originally posted as https://github.com/aspnet/Mvc/issues/2822 from @mbharodia 

I have several helper classes.

One of them is a custom implementation of ILogger and ILoggerProvider. I wanted to provide configuration value to ILogger such as file path to log values. I wanted to inject IOption<AppSetting>.

My custom ILogger is created by my custom ILoggerProvider. If I do constructor injection then I need to pass in this dependency all the way up to ILoggerProvider.

So thought to use [FromServices] right in ILogger. When I used [FromServices] on a property, it did not resolve the dependency.

**Comment by borgdylan** [comment]
FromServices is an Mvc-ism.

**Comment by csunali** [comment]
I am in a similar situation and need to inject a service to my Logger Provider or my Logger. So, how about adding a provider using its type rather than an instance?

Currently, we are adding new providers using the following code and we need to construct all dependencies ourselves. 

```
loggerFactory.AddProvider(new MyLoggerProvider());
```

That becomes a problem if we still don't know what would be the exact type of the dependency until we have the complete graph.

If you have let us use the following code and resolve the constructor dependencies at runtime, that would be of great help:

```
loggerFactory.AddProvider(typeof(LoggerProvider));
```

Saying that because we might not have the dependencies initialized at the time of adding a provider.

If my approach is wrong, please lead me to the correct implementation.

**Comment by muratg** [comment]
@lodejard Thoughts?

**Comment by lodejard** [comment]
IoC container isn't ready to provide services until you reach the `Configure` method - `Startup` constructor and `ConfigureServices` methods are too soon.

To do what you're attempting try adding `MyLoggerProvider` to the container inside `ConfigureServices`. Then once you're in the `Configure` method do `loggerFactory.AddProvider((ILoggerProvider)services.GetService(typeof(MyLoggerProvider))` - then you should be able to use DI and IOptions in your provider's constructor.

**Comment by pakrym** [comment]
```
services.AddSingleton<ILoggerProvider, MyLoggerProvider>();
```
works now.
