### ISSUE TITLE
EventId a string instead of int

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Logging#226]
Can you explain a little more what the purpose of the `eventId` parameter is, and why it is an int currently? My understand of how this can be used is as a logical grouping of logs that can be filtered on some common "event id".

If this understanding is correct, I would expect eventIds be more flexible to match ids that fit my data source, namely Guids and strings. A string would be the most flexable since I could easily `.toString()` any id type.

**Comment by glennc** [comment]
The intent here is that a given event id is for a specific event, rather than a logical grouping of events. Such as event 532 means that I couldn't connect to the database. Event 533 means that a user failed to login, something of that sort.

As such we felt that an integer made the most sense for the field.

**Comment by kspearrin** [comment]
Ok, that makes sense then. Thanks
