### ISSUE TITLE
ConsoleLogger doesn't use LoggerFactory.MinimumLevel by default

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/Logging#247]
See this line: https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Console/ConsoleLoggerFactoryExtensions.cs#L16

This means the following doesn't result in verbose messages being emitted:

``` csharp
loggerFactory.MinimumLevel = LogLevel.Verbose;
loggerFactory.AddConsole();
```

**Comment by herecydev** [comment]
Whilst I get while it may feel counter-intuitive for you to explicitly set the `MinimumLevel` and for it not to be actioned, the XML documentation clearly states it's for information or higher. An overload is provided for just what you want.

However, I would agree that making decisions (i.e minimum of information) on behalf of the user is dangerous, and at absolutely minimum should respect the `ILoggerFactory`. If the decision was made that information should be the minimum then this should be placed onto the `LoggerFactory`, thus forcing this behavior onto any implementation of `ILogger`.

**Comment by Eilon** [comment]
This isn't a bug, it's by design. The minimum level indicates that any logs below the specified minimum will not even be seen by loggers, no matter how hard they try.

It is entirely unrelated to the level at which a particular logger will record/save/transmit/render logs.

The console logger, in order to minimize noise, chooses by default to render only Information and higher. Other loggers can choose to have their own appropriate defaults.
