### ISSUE TITLE
Question about FileLogger implementation

### ISSUE THREAD

**Issue by dmitry-ra** [aspnet/Logging#250]
Do you plan or wish to implement the FileLogger as part of the aspnet/Logging project or it should be a third-party provider? I have interest to contribute to this feature, but I don't know where it should be.

**Comment by Eilon** [comment]
No current plans for this, mostly because there are a lot of great comprehensive solutions that already exist. I think having such a feature built-in would be nice, but I suspect it's a huge amount of work due to what is likely to be a large "minimum viable implementation." Having said that, it's certainly worth a discussion.

**Comment by muratg** [comment]
I wonder why folks would choose not to use NLog or SeriLog for logging to a file. 

Putting in Backlog for further discussion.

**Comment by w438418754** [comment]
NLog project integration is too low ,They don't have a unified style.

**Comment by muratg** [comment]
Discussion: https://github.com/aspnet/Logging/issues/441

Closing this as a dup
