### ISSUE TITLE
Proposal: Decorate methods with JetBrains.Annotations.StringFormatMethodAttribute

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Logging#340]
Proposal to decorate the log methods with the [`StringFormatMethodAttribute`](https://www.jetbrains.com/resharper/help/Reference__Code_Annotation_Attributes.html#StringFormatMethodAttribute). 

Example:

``` c#
[StringFormatMethod("message")]
public static void LogDebug(this ILogger logger, EventId eventId, 
           Exception exception, string message, params object[] args)
```

You get then help from Resharper, including validation of the format message. 

Is a PR accepted on this one? (after merge of https://github.com/aspnet/Logging/pull/338 I guess)

**Comment by Eilon** [comment]
Interestingly, in the particular case of the logging APIs they are *not* `string.Format` arguments and those are specifically dis-recommended. That is, instead of `The value of {0} is {1}` you should pass in `The value of {foo} is {bar}`. This allows structured logging to have named key/value pairs.

But to answer the more general question: each repo has slightly different views on the JetBrains annotations because different parts of the team work on them. The data-oriented repos (e.g. EF) use them heavily, but most others do not use them at all. This largely varies based on who uses R#. As such, I'd leave it to the folks who work the most on this repo to chime in on that specific aspect.

**Comment by 304NotModified** [comment]
Thanks for the feedback! 

At NLog we use the JetBrains annotations are there is no downside on it. (And IMO everyone should use R#)

**Comment by Eilon** [comment]
The downside is having a lot of annotations :smile:

**Comment by muratg** [comment]
Thanks @304NotModified for the suggestion! Agreed with Eilon, since the recommended approach is using c# string interpolation, I don't think this particular attribute would be useful, and would also be needed to added all over the place. Backlogging this for now.

**Comment by pakrym** [comment]
`.Log` is not `string.Format` methods and marking them with `StringFormatMethod` would be wrong.
