### ISSUE TITLE
Is current implementation too pervasive?

### ISSUE THREAD

**Issue by chaim770** [aspnet/Logging#359]
Following this StackOverflow post:
http://stackoverflow.com/questions/35251078/

It's seems like by default, all vendor code logging (Like `Microsoft.*` as well as other packages) would go through the configured log providers as well.

Isn't it a good idea to be able to easily disable frameworks/vendor libraries logging? Or perhaps expose a way to filter out (or set logging-level per) Types on the `ILogger`/`ILoggerFactory` itself?

**Comment by gdoron** [comment]
I can understand the reasoning here, this is the only way that gives the application the flexibility of having each logger log different logging sources and severity.

I just think that once my application will grow to use let's say 20 middlewares it will be very difficult to keep track of which middleware is writing which logs etc.

I'm not sure there's a better design than what current we have, but it sure is very annoying writing LoggerProvider now.

**Comment by nblumhardt** [comment]
All of the events through the new logging pipeline carry a bag of structured data that can be used to manage this. For example if you send the logs through Serilog, a `SourceContext` property gets attached like the one in the second-last line below:

![image](https://cloud.githubusercontent.com/assets/342712/12875911/34265ce4-ce40-11e5-9f86-a760cfaa980d.png)

This means you can exclude logs in a more fine-grained manner, e.g. in Serilog:

```csharp
    .Filter.ByExcluding(Matching.FromSource("Microsoft"))
```

Or in a back-end log store:

```
!StartsWith(SourceContext, "Microsoft.")
```

Having all the events (user and framework) going through the same pipeline means you can be more selective about what's emitted, as long as you're able to access the properties attached to the events.

While a lot of the framework's internal events will be uninteresting most of the time, there are a few (request starting, request finished, errors) that are pretty much always worth collecting. Using separate pipelines would put a barrier here IMHO.

**Comment by chaim770** [comment]
@nblumhardt That's exactly the issue here. The current logging infrastructure does not expose anything such as your mentioned `SourceContext` nor `Filter`.

Although each provider can definitely opt in and out of some sources, it will be much clearer to expose that functionality on the common logging *interfaces* as well (such as `ILoggerProvider`).

**Comment by nblumhardt** [comment]
Hi @chaim770 - the event shown above was generated by the current logging infrastructure (RC1) - not sure what you mean?

When it's passed to _Serilog_ we rename it `SourceContext` for consistency with other Serilog events, I think it comes through the _Microsoft.Extensions.Logging_ pipeline as "category name".

Let me know if I've misunderstood :-) Cheers!

**Comment by gdoron** [comment]
@muratg @nblumhardt I can not think of a real application where a (DB/File/EventViewer) logger would log everything that ASP.NET tunnels through the logging on debug.
Each request will lead to more than 15 log entries just from ASP.NET logs.

So I believe it's mandatory for the ILogger to be changed to something like:

`bool IsEnabled(string source, LogLevel logLevel);`

Because without knowing the source (EF/ASP.NET/ my application) the LogLevel is worth nothing.

**Comment by muratg** [comment]
@gdoron We will just need a really good design for this if we ever want to support this at the base logger level. As @nblumhardt mentions, this is possible with certain implementations.

Adding a `string` based `IsEnabled` method may not be the best way to go for it.

cc @lodejard @davidfowl @DamianEdwards @Eilon for their thoughts on this.

**Comment by chaim770** [comment]
@muratg It already implemented (to some degree) in `ConsoleLogger` using `Func<string, LogLevel, bool>`.

See https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerFactoryExtensions.cs#L80

**Comment by muratg** [comment]
@chaim770 Yup, I think it's fine to do it in some specific implementations, but to me forcing ALL the implementations to do it via exposing it in the interface does not seem right.

**Comment by gdoron** [comment]
@muratg question is do you think it's possible for a logger not to filter the messages tunneling through by the LogLevel **and** by the source?
I think the answer is no. If a logger will log every debug message ASP.NET or other middleware sends through the pipeline, not just it will be a serious performance bottleneck in the a application but it will also make the log unusable since it will be full of "noise".

So since this filtering is a must for a logger and without it the logger is unusable, IMHO it should be part of the ILogger/ILoggerFactory interface.

**Comment by davidfowl** [comment]
It's the wrong place to filter. The ILoggerProvider already has this information. When you create a logger, it's for a specific category/source. I think what you're asking for is a sink agnostic way to filter log messages. You're supposed to rely on the sink implementation of your choice to do that filtering.

That's what @nblumhardt was referring to earlier

**Comment by TsengSR** [comment]
@gdoron:

It's not about the logger, it's about the logger provider. 

As I've posted it in the SO comment already, the logger provider wraps around the actual logger library (except for the most simple logging like console logging, where it also directly logs the message). Since neither the application framework you use (ASP.NET MVC for example or the hosting system) knows about the logging library and it's specific nor does the logging library know about implementation detals of the ecosystem it's used in, you need the logger to translate the calls from one to the other. 

If the logging library has a concept of "sourcecontext", "category" or whatever you want to call it, it's just a matter of passing this value to the logger and have the logger library handle it as per it's configuration. 

If the logging library doesn't have such an concept, you need to filter the message before they are passed to the logger library. This would be the logger provider. 

If a logger has such filtering concepts (log levels, categories, sources, etc.) depends on it's implementation

**Comment by lodejard** [comment]
The ILogger.IsEnabled(level) already knows what the source string is - because the ILogger was created for a specific source. It can be more efficient that way because IsEnabled doesn't need to do any string comparisons per-log-call at runtime.

The logger factory itself shouldn't have any filtering policy because the third party logging providers you choose to add are expected to each have filtering and dispatching capabilities. It would be pretty awful for the system to always have two different filtering mechanisms in those cases.

Something that might be interesting would be to have a filtering ILoggerProvider wrapper. It wouldn't be part of the logger factory itself, but a decorator-pattern wrapper like that could give you a consistent filtering mechanism that you could opt-in to having around any providers you add.

That said - it might be a little tricky to get that to work through extension methods... Not impossible - but definitely clearer what's happening if you use the provider ctors directly...

**Comment by gdoron** [comment]
@lodejard that makes perfect sense now, thank you very much for the answer!
I just didn't understand the wrapper idea, can you please give an example for such a wrapper?

**Comment by lodejard** [comment]
@gdoron wow, I very rarely get a reply "that makes perfect sense". Thanks! :)

Here's an example of a filtering logger provider https://github.com/aspnet/Logging/commit/bf2314a9a139ae04fd7310d5df99b0cbe968ae35#diff-459e7bd4d619a1efc2739dff9398cf91R28

It's in a different assembly independent of the logger factory and providers, so it's completely opt-in and you can put it in place like this:
```cs
    /// How to wrap filtering provider around other providers
    factory
        .WithFilter(new FilterLoggerSettings
        {
            { "Microsoft", LogLevel.Warning },
            { "System", LogLevel.Warning },
            { "SampleApp.Program", LogLevel.Debug },
        })
        .AddEventLog();
```

**Comment by chaim770** [comment]
@lodejard Thanks for the explanation.

> Something that might be interesting would be to have a filtering ILoggerProvider wrapper. It wouldn't be part of the logger factory itself, but a decorator-pattern wrapper like that could give you a consistent filtering mechanism that you could opt-in to having around any providers you add.

My initial post on this issue indeed mentioned `ILoggerProvider` as a possible candidate for filtering.

**Comment by gdoron** [comment]
@lodejard Thanks for the demo, really neat, I always liked fluent decorator API.
I'll tell you what, whenever one of the _Scott_s are giving you hard time at the office ping me and I'll say you make perfect sense. ;)

**Comment by lodejard** [comment]
@chaim770 ah, yes! good idea :)

**Comment by ejsmith** [comment]
So my question is, how do we as library authors keep from flooding the consumer applications logs without them having to explicitly add filters for our categories?

**Comment by gdoron** [comment]
@ejsmith The library can be more restrictining and requires a filter.
An implementation can always be more restricting thean the interface.

**Comment by ejsmith** [comment]
@gdoron not sure how that would work? Any samples?

**Comment by gdoron** [comment]
You can check the examples above, like the console logger, or the filter logger https://github.com/aspnet/Logging/commit/bf2314a9a139ae04fd7310d5df99b0cbe968ae35#diff-459e7bd4d619a1efc2739dff9398cf91R28

https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerFactoryExtensions.cs#L80
