### ISSUE TITLE
Why and What is EventId?

### ISSUE THREAD

**Issue by niemyjski** [aspnet/Logging#367]
I'm wondering why I need it and what is it for? Why is there an overload that makes it only required when you log exceptions?

https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/ILogger.cs#L22

**Comment by jamie94bc** [comment]
In [LoggerExtensions.cs](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs) there is an overload where it's not required, but it is required when logging exceptions?

```c#
public static void LogDebug(this ILogger logger, EventId eventId, Exception exception, string message, params object[] args)
public static void LogDebug(this ILogger logger, EventId eventId, string message, params object[] args)
public static void LogDebug(this ILogger logger, string message, params object[] args)
```

**Comment by ejsmith** [comment]
There is another issue asking for an extension method without it for logging errors.

**Comment by cwe1ss** [comment]
#294 is the related issue

**Comment by ejsmith** [comment]
I think the EventId is pretty useful. Allows easily finding specific log messages and also allows doing asserts in tests for those messages based on the event id.

**Comment by niemyjski** [comment]
Yeah but it almost should be an internal detail and not something I have to specify on every log message :(

**Comment by ejsmith** [comment]
You don't specify it on every log message. There are extension methods that don't require it and they also encourage you to build delegates for log messages so you end up just calling something like this:

`_logger.OrderPlaced(order);`

This makes the logging even faster and more succinct.

**Comment by cwe1ss** [comment]
I totally agree that it is useful but I'm also pretty sure most people won't use it. Almost no one has used this concept during the last 10 years - so changing this will be a long process for many.

I'm all for making the API as easy as possible. First priority should be to make sure, people can write log statements as easy as possible. The quality of the messages can be improved later. 
It's already complex enough to inject the logger all the time. This is the great thing about Serilog - you just write Log.* somewhere and that's it. (Of course, you don't have any context in that case but it's up to the developer to decide if he wants it or not)
There are so many cases where you just want to write a log statement in your completely awful static helper method and you don't want to think about Dependency Injection because it's just not worth it. 
We constantly have a discussion about introducing a static log accessor for that reason. 

Life's just not as perfect as we want it to be. :-)

**Comment by ejsmith** [comment]
Yeah, I'm in the process of switching my library [Foundatio](https://github.com/exceptionless/Foundatio) over to use injected loggers instead of a static logger and its a bit of a pain, but it also seems to be paying off in testing and other benefits.

**Comment by baoduy** [comment]
sometimes I just want to log the exception details include StackTrace without EventId, hope that the new overload extension method for it will be added in near future.

**Comment by JimmyBoh** [comment]
@baoduy Here is my workaround:

```csharp
using System;

namespace Microsoft.Extensions.Logging
{
    public static class LoggerExtensions
    {
        public static void LogError(this ILogger logger, Exception ex, string message = null, params object[] args)
        {
            logger.LogError(default(EventId), ex, message, args);
        }
    }
}
```

**Comment by baoduy** [comment]
@jimmyboh
Yes, thanks for your reply. I also did the same.

**Comment by MNF** [comment]
Core 2.0 includes extension overloads without EventId
