### ISSUE TITLE
Redundant words in the API signature

### ISSUE THREAD

**Issue by niemyjski** [aspnet/Logging#368]
I was looking [at the API](https://github.com/aspnet/Logging/blob/4528bdbc2816a8b5f933d9c6cf2da806ce4a72ea/test/Microsoft.Extensions.Logging.Test/LoggerExtensionsTest.cs#L34-L39) and thought it was pretty verbose (VB???)

```csharp
 logger.LogTrace(_state);
            logger.LogInformation(_state);
            logger.LogWarning(_state);
            logger.LogError(_state);
            logger.LogCritical(_state);
            logger.LogDebug(_state);
```

Your variable name is almost always going to contain the word log, and now the method call also contains log. Is there any reason for this? To me it's more verbose then it needs to be.

**Comment by ejsmith** [comment]
Completely agree. Personal pet peeve of mine when method names are redundant with the type name. Just seems unnecessary and verbose.

**Comment by cwe1ss** [comment]
I would also prefer method names without the Log-prefix. That's how many other libraries do it. But I'm afraid it's way too late to change this :-(

**Comment by ejsmith** [comment]
Yep, I'm pretty sure every other logging abstraction uses the same names. So not sure why the decision was made to use more verbose and redundant names.

Now is the time to change this. There have already been several breaking changes since RC1. I'm not sure if the team realizes that this library is going to be used by the entire community of library authors.

Common Logging:
https://github.com/net-commons/common-logging/blob/master/src/Common.Logging.Core/Logging/ILog.cs

NLog:
https://github.com/NLog/NLog/blob/master/src/NLog/ILogger.cs

log4net:
https://github.com/apache/log4net/blob/trunk/src/ILog.cs

**Comment by cwe1ss** [comment]
I would also like to see this library getting adopted in as many places as possible! That would be a huge win for everybody. It just needs a few more minor improvements like this. I'm ok with breaking changes - that's a perfect example for why search and replace was invented! :-)

**Comment by Eilon** [comment]
Hi folks, at this time we are not looking to change the names of these APIs. (I, for one, like having the Log prefix in the name because it makes it easier for me to grep teh codez to find these calls.)

**Comment by niemyjski** [comment]
And that's that? You realize that your grep command would pick up `log` in
_log.LogError() twice right?

Thanks
-Blake Niemyjski

**Comment by Eilon** [comment]
We discussed this amongst several folks on the project and decided that at this time the change isn't worth it. This type of change takes a lot of time to do because there are hundreds (if not thousands) of calls to it across dozens of GitHub repos, and that's just within ASP.NET/EF - there are countless other projects around the world using this interface already and they would all be affected. We only make such changes if we think they are truly necessary - such as renaming the product to reduce confusion (which caused almost all packages + namespaces to change). That was a very, very painful change for everyone.

**Comment by niemyjski** [comment]
@Eilon The time to change this is now before you have MILLIONS of packages depending on this... You can't make the argument that there are countless other projects using it.. You guys already broke the implementation between RC1 and RC2. Who cares if it's a pain now, lets do it before a RC (the last rc should have been a beta).

**Comment by BillHenning** [comment]
It does seem very redundant to have Log in the various extension method names when the primary target class name is Logger.

**Comment by Bartmax** [comment]
:+1: +1 to change it now.

**Comment by benaadams** [comment]
Its on the interface? So would have something like
````csharp
messageDisptacher.LogTrace(_state);
messageDisptacher.LogInformation(_state);
messageDisptacher.LogWarning(_state);
messageDisptacher.LogError(_state);
messageDisptacher.LogCritical(_state);
messageDisptacher.LogDebug(_state);
````
Is only duplicated because of the variable name

**Comment by Eilon** [comment]
Folks, we understand the feedback, but we're talking about removing three characters from a method name.

This is ultimately a subjective matter and we think having the `Log` prefix is nicer than not having it.

**Comment by niemyjski** [comment]
It's going against the grain for all the existing sources of work, which makes it harder to migrate to this logging implementation, more verbose and is unfamiliar to developers. If it's just three characters then remove them :)

**Comment by ejsmith** [comment]
For me, the problem is that the abstractions package includes a bunch of extension methods that are in the same namespace. So if we wanted to build our own extension methods on top of the ILogger interface, they might conflict with the existing ones. 

Why not move the extension methods into a separate nuget package and keep this package as truly just the logging abstractions?

I think this library could be AWESOME for the community if we keep it ridiculously simple and put your opinions in a separate package of extension methods.

**Comment by niemyjski** [comment]
I agree with that completely and it would solve this.

**Comment by cwe1ss** [comment]
there are other more important issues, so I think time is spent better there.

We will get used to this...

**Comment by cwe1ss** [comment]
@ejsmith but this way everyone would have to reference two packages / namespaces. That seems counterintuitive.

If you don't mind writing your own extension methods, why not just add aliases without the "Log" prefix yourself in your base library?

**Comment by benaadams** [comment]
@ejsmith you probably don't want to use these extension methods by default anyway and do something more like [IKestrelTrace](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Infrastructure/IKestrelTrace.cs) and [KestrelTrace](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Infrastructure/KestrelTrace.cs); so its good they are clustered together in alpha/intellisense

**Comment by ejsmith** [comment]
@cwe1ss yes they would, have you used .NET Core?  EVERYTHING is a package. Every package has about 20 other packages that it depends on.  So why would we be worried about 1 more?

@benaadams I agree, so let's get these extension methods out of this lib. :-)

**Comment by benaadams** [comment]
@ejsmith but to a new user `Action` `Nounish` e.g. `LogError` might be helpful whereas just `Error` is that an action that creates an error? Like `ThrowException`?

**Comment by ejsmith** [comment]
@benaadams right now you are making all these nice typed log messages for your logger, but there are a bunch of extension methods on your logger that you don't want anyone using as well. Wouldn't it be nice to get those out of there?

The point is that those extension methods are very opinionated. This library has GREAT potential to make logging in .NET a LOT better than it has been in the past. Now is the time to remove the extra stuff and just have the abstractions in this package. It's not hard to add an extra package that has the opinionated logging helpe methods in it.
