### ISSUE TITLE
Consider adding a 'correlationId' middleware

### ISSUE THREAD

**Issue by rynowak** [aspnet/Logging#371]
It's a common pattern (like WCF activity ID) to create a correlation id and use it across multiple services with logging. This way if your logs all go to the same store you can associate all of the business processes across service/server boundaries that are part of the same unit of work. 

1. Front-end server creates a correlation ID and creates a log scope
2. Front-end server stashes the correlation ID in a way that some other code can get it (http context extension?)
3. Front-end server makes a call to another service - propagates the ID by taking it out of http context and passing it via a header (http client)
4. Back-end server reads the header and creates a log scope
5. And so on...

There's 3-5 lines of boilerplate required to do steps 1,2, and 4, and we could easily make a middleware that does it for you.

We might want to add an extension method for step 3.

**Comment by ejsmith** [comment]
I don't think anything in the core interfaces needs to be changed for this, right? If so, this type of functionality really needs to be in another package. I am personally trying to get them to move all extension methods out to another package because the simpler we keep this abstractions package, the more chance it has of becoming the defacto standard for .NET logging and that would be a huge win.

**Comment by davidfowl** [comment]
This should be moved to either basic middleware or hosting

**Comment by rynowak** [comment]
> If so, this type of functionality really needs to be in another package. 

Yup. That's how we'd do it.

**Comment by muratg** [comment]
This issue was moved to aspnet/BasicMiddleware#32
