### ISSUE TITLE
Add suffix "Provider" to AddConsole, AddDebug and similar methods (methods rename)

### ISSUE THREAD

**Issue by deni35** [aspnet/Logging#419]
When I first saw AddDebug or AddConsole methods It was not clear to me what are these methods doing.
If you name these methods with suffix "Provider" it would be more intuitively.

```
loggerFactory.AddDebugProvider(...)
loggerFactory.AddConsoleProvider(...)
```

**Comment by 304NotModified** [comment]
I think `AddConsole` is clear, but `AddDebug` isn't.

**Comment by deni35** [comment]
When I started working with logging, I did not know about providers. So, I didn't understand what these methods do.

**Comment by cwe1ss** [comment]
My main critique still is that providers shouldn't be added to a ILoggerFactory. Instead, there should be e.g a `ILoggerProviderFactory` because creating loggers and adding providers are two completely different concerns. Having `AddConsole`/`AddDebug` on this separate class would make it clearer IMO.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
