### ISSUE TITLE
Consider targeting .NET Framework in addition to .NET Standard

### ISSUE THREAD

**Issue by roji** [aspnet/Logging#550]
The new version of Npgsql (PostgreSQL driver for .NET) depends on Microsoft.Extensions.Logging as a logging abstraction, it's great to have it.

However, [users have been complaining](https://github.com/npgsql/npgsql/issues/1430) about the very large number of package dependencies that have been added to Npgsql when targeting .NET Framework. The cause of this is that Microsoft.Extensions.Logging (and its various dependent packages) targets .NET Standard (1.1), which brings in a whole lot of dependencies.

Now, I've read https://github.com/aspnet/HttpSysServer/issues/268 and other related issues and I fully understand why this is happening, that it makes sense, and also that the DLLs themselves simply forward to the .NET Framework assemblies in the GAC. On the other hand, my library has gone from zero dependencies to a great deal simply by taking a dependency on Microsoft.Extensions.Logging, and this is bothering both me and my users.

A simple fix for this would be for packages such as this to target .NET Framework in addition to .NET Standard. I fully understand that this would have to be propagated across lots of packages (e.g. dependency injection), and that it serves no other purpose than to clean up bloat which doesn't dramatically affect things.

So I'd fully understand if you don't want to make any changes to address this - but I wanted to bring it to your attention that users don't really appreciate it very much.

**Comment by natemcmaster** [comment]
This is an issue that has been raised several times. It will be fixed as we move our libraries to .NET Standard 2.0. Unlike 1.x versions of .NET Standard, .NET Standard 2.0 will be one package.

See https://github.com/dotnet/standard and https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/ for more details on .NET Standard 2.0.  See https://dotnet.myget.org/feed/dotnet-core/package/nuget/NETStandard.Library if you want to test out nightlies.

**Comment by roji** [comment]
@natemcmaster that's great to hear, I wasn't aware .NET Standard 2.0 will resolve this.

Just to be absolutely sure I understand, once .NET Standard 2.0 is out, an application targeting .NET Framework, say, 4.5.1 (or netcoreapp11) will be able to take a dependency on a .NET Standard 2.0?

**Comment by natemcmaster** [comment]
.NET Framework 4.6.1 already has the API to make it compatible with .NET Standard 2.0. We’ll ship updated versions of .NET Core, Xamarin, and UWP that will add all the necessary APIs for supporting .NET Standard 2.0.

**Comment by nzain** [comment]
While this issue is closed, I'd like to point out what the actual solution is right now (netstandard2.0 is out), because it is not that obvoius and it doesn't work automagically.

*Scenario A: Direct Project References*
Net Framework Applications can reference a netstandard library without extra dependencies.

*Scenario B: netstandard NuGet Packages*
A nuget package might target `netstandard1.0` (or 2.0 or whatever version) and nothing else. Installing this nuget package from a Net Framework application _will_ pull 46 confusing dependencies, even if your application's target framework is compatible.

Multi-targeting will resolves the problem. The package maintainer can specify
```
<TargetFrameworks>netstandard1.0;net45</TargetFrameworks>
```
which will create two layers in the nuget package: `netstandard1.0` and `net45`. The second one can be consumed from net framework applications without package pollution / confusion.
