### ISSUE TITLE
Remove "breaking changes" after ApiCheck is fixed.

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Logging#780]
@javiercn and I believe this is a bug in ApiCheck, so we added exclusions for now, but we should revert those exclusions once aspnet/BuildTools#615 is closed. The offending items are:
```
[
    {
        "TypeId": "public class Microsoft.Extensions.Logging.Abstractions.NullLogger<T0> : Microsoft.Extensions.Logging.ILogger<T0>",
        "Kind": "Removal"
    },
    {
        "TypeId": "public class Microsoft.Extensions.Logging.Abstractions.NullLoggerFactory : Microsoft.Extensions.Logging.ILoggerFactory",
        "Kind": "Removal"
    },
    {
        "TypeId": "public class Microsoft.Extensions.Logging.Abstractions.NullLoggerProvider : Microsoft.Extensions.Logging.ILoggerProvider",
        "Kind": "Removal"
    }
]
```

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface. Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. See https://github.com/aspnet/BuildTools/issues/747
